### ISSUE TITLE
Cmake error for OSX

### ISSUE THREAD

**Issue by EasonWang01** [Blizzard/s2client-api#101]
```
➜  build cmake ../ -G Xcode
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at contrib/civetweb/cmake/DetermineTargetArchitecture.cmake:30 (execute_process):
  execute_process attempted to output into a file: into a source directory.
Call Stack (most recent call first):
  contrib/civetweb/CMakeLists.txt:37 (determine_target_architecture)


-- Configuring incomplete, errors occurred!
See also "/Users/lin/s2client-api/CMakeFiles/CMakeOutput.log".
See also "/Users/lin/s2client-api/CMakeFiles/CMakeError.log".
```

**Comment by kuzi117** [comment]
You're trying to do an in source build (generating object file alongside coffee which is frowned upon for polluting the source tree.

Instead, from your root source directory, `mkdir build && cd build && cmake .. -G Xcode`. You can actually build to any directory other than your source directory if you'd prefer to have your build directory elsewhere. Look up out of source building for more info

**Comment by kuzi117** [comment]
Actually, after looking at the error again, sorry I just woke up, are you already building into a build folder separate from your source tree?

**Comment by EasonWang01** [comment]
Was in the CMakeLists.txt folder and `mkdir build && cd build && cmake ../ -G Xcode`
and the same error.

**Comment by KevinCalderone** [comment]
So your folder structure looks like this right?
/Users/lin/s2client-api/build/

Also if there are any generated cmake files from your earlier attempts, make sure to delete those before trying again.

**Comment by Skarlso** [comment]
Interestingly enough I just did this on OSX and it works fine. :/ Though with a LOT of deprecation warnings. :)

**Comment by Skarlso** [comment]
Actually, wasn't civetweb just updated? 

Maybe refresh your local submodules and try again? Also, what @KevinCalderone is saying. Your folder target should be s2client-api/build. And being there, `cmake .. && cmake --build .`.

**Comment by EasonWang01** [comment]
Thanks,it solved by remove the folder and clone then cmake again.
