### ISSUE TITLE
Add stableid.json and stableabilityid.json to version control

### ISSUE THREAD

**Issue by Dentosal** [Blizzard/s2client-api#102]
[`sc2_typeenums.h`](https://github.com/Blizzard/s2client-api/blob/master/include/sc2api/sc2_typeenums.h) mentions these files:

> All units and abilities are represented as unsigned numbers in the StarCraft II engine. This can make issue abilities unnecessarily hard.
This file aims to provide a type safe and named way of representing unit types and ability types. Entries in it are generated by a custom
built script so it is possible they don't have every possible id in the engine but they should have most of the common ones.
See stableid.json and stableabilityid.json to see all of them.

I'm unable to find these files, and I think it would be useful to have them published here. (or maybe in the [proto repository](https://github.com/Blizzard/s2client-proto)).

**Comment by KevinCalderone** [comment]
That comment is a bit out of date. Those used to be loose files, but now they are included in the game installation.

The id mapping those files define is the same as what is output by ObservationInterface::GetUnitTypeData. This is the most reliable place to find this data.

For the common id's at least, we were thinking about exposing that list in the proto files themselves. (See Blizzard/s2client-proto#16)

Technically you can actually find this file in your SC2 documents directory:
C:\Users\username\Documents\StarCraft II\stableid.json

I wouldn't rely on looking at this file though as we may remove/move it in the future. (We were planning on allowing you to override the id mapping with this file, but never got around to implementing it. The file is still sitting there though.)

**Comment by spacekitteh** [comment]
Since the `stableid.json` file seems to no longer be part of a game install, is there some alternative reference document for the mapping, other than the header file? Or do new language bindings just have to munge it?
