### ISSUE TITLE
Linking api in Linux (might be I who lack knowleage)

### ISSUE THREAD

**Issue by mejan** [Blizzard/s2client-api#104]
Hej!

I might be an idiot to ask this question but I run Linux (ubuntu 16.04 gnome). So I followed your build instructions (copy paste each line (3-4 times to be sure)). Anyway normally when I install/build Libary for c++ a link or file is added to /usr/include (the header file) in this case no. So I've tried with softlinks to the actually folder where the api header files is like:
``
#! /bin/bash
pathApiDir=/home/userName/src/s2client-api/include
pathToApi=$pathApiDir/sc2api
pathToLib=$pathApiDir/sc2lib
pathToRenderer=$pathApiDir/sc2renderer
pathToUtils=$pathApiDir/sc2utils
sudo ls -s $pathToApi /usr/include
sudo ls -s $pathToLib /usr/include
sudo ls -s $pathToRenderer /usr/include
sudo ls -s $pathToUtils /usr/include
``
I did it this way due to in the #include you have as an example you use <sc2api/sc2_api.h> which would be perfect in my opinion. I've also added to project makefile all the *.cc files in s2client-api/src folder to make sure that all will be included still get the error: "sc2api/sc2_api.h: No such file or directory". I tried different linking flags as: "-lsc2", "-sc2", "-lsc2api" and more.

I do not get way I can't seem to compile the file /s2client-api/project/project/main.cpp

Is it some step I miss or something?

as said earlier this might be a stupid question.

**Comment by kuzi117** [comment]
Two things:
1. there is no install target right now, if you want to find sc2api automatically you might consider the cmake solution that CommandCenter uses. Otherwise, if you wait, I'm working on installing things in #90.
2. It seems like is not set up to build using the cmake build. The directory also contains a project for building on windows, I'm not sure this was supposed to be anything other than a windows test. Currently on my branch I can manually get this to compile using `c++ main.cpp -std=c++11 -lsc2api -lsc2protocol -lsc2utils -lprotobuf -lcivetweb -ldl -lpthread` but this is _only_ after fairly significant additions to the build script.

**Comment by mejan** [comment]
It is great that you are working on a install target. But not to sound "ungrateful" or anything but what do you estimate this target solution to? Also you don't care to share the significant additions to the build script?

Again apologize if I sound ungrateful!

**Comment by kuzi117** [comment]
Currently, it's used as part of a cmake build for my own project. I created a SC2APIConfig for cmake so you can use `find_package` to just have the include directories and libraries provided to you. If you aren't using cmake then the benefits are that it installs all of the headers from the api as well as the libraries you want to link against (as in the above command I showed to compile `project/project/main.cpp`).

I'm not trying to hide anything, I've discussed creating a pull request in the issue I linked above. All changes made are up-to-date in my fork of the repo available publicly on my profile. If you want the differences, here they are: https://github.com/Blizzard/s2client-api/compare/master...kuzi117:master. One thing to note that I haven't updated is the contrib repos. Those are still behind what I need them to be (on github). I've updated them locally, but the process is fairly easy. Just `cd` to the nested repos and `git checkout master` until someone chooses the a tag to change them too officially.

**Comment by KevinCalderone** [comment]
Closing this for now to keep our list clean.

It doesn't seem like there is anything left actionable here other than working toward having a cmake install target, which is being tracked by #90.

If you are still trying to get this to work manually, feel free to post here again.
