### ISSUE TITLE
Apparently meaningless "weapon_cooldown" values

### ISSUE THREAD

**Issue by Rokhan** [Blizzard/s2client-api#105]
Hello,

   I tried to modify the "MarineMicroBot" example and use "weapon_cooldown" of the units in "MarineMicroBot::OnStep" methods. Surprisingly, weapon_cooldown has very strange values : it's nearly always 0.0 and sometimes a random value between 10.0 and 15.0.

I would have expected something that reduce a little at each step and go back to a max value when the unit has just shot.

Regards

**Comment by davechurchill** [comment]
What is your step size? If it's not 1 then you may be missing intermediate frames where the cool down is resetting over time.

**Comment by Rokhan** [comment]
I keep the default value, so stepSize = 1.

**Comment by davechurchill** [comment]
Try printing a unit's cooldown whenever it's not 0 and see if it is in fact ticking down each frame

**Comment by Rokhan** [comment]
Here is a very simple patch  based on master showing the problem, the output of bot_micro running on my pc and a grepped version of the output to remove all "cd = 0".

* [bot_micro_stdout.txt](https://github.com/Blizzard/s2client-api/files/1243619/bot_micro_stdout.txt)
* [bot_micro_stdout-without_null_cd.txt](https://github.com/Blizzard/s2client-api/files/1243620/bot_micro_stdout-without_null_cd.txt)
* [bug_cooldown.diff](https://github.com/Blizzard/s2client-api/files/1243624/bug_cooldown.diff.txt)

**Comment by KevinCalderone** [comment]
Yeah that data does look strange. I'll see if I can repro.

**Comment by davechurchill** [comment]
Are you storing the unit pointers over multiple frames and using that to get the CD or are you storing the tag and calling getUnit every frame? If you are doing the former you're probably getting junk data from invalidated pointers.

**Comment by Rokhan** [comment]
No, the behaviour is visible by just adding some output to the bot_micro example. (the sort doesn't change the result, it just order units by tags in output)

**Comment by KevinCalderone** [comment]
Ok there appears to be a bug in how the game is reporting the value. It stops outputting the value as soon as the attack animation finishes, which is why it jump back to 0 suddenly.

This will require a game patch to fix so it will be broken for a little while unfortunately. Thanks for the easy to use repo steps! We will fix.

**Comment by KevinCalderone** [comment]
This has been fixed in the game. It was too late to sneak it into our next patch, but it will be in the patch after that.

**Comment by davechurchill** [comment]
Kevin: Could you also possible expose "isAttackAnimation" to us? It would be useful to know the time period where the unit is no longer firing, but still has cooldown remaining, for purposes of kiting

**Comment by KevinCalderone** [comment]
I would guess the goal is to know the exact timing where you can move the unit away and still have the damage go off? I think usually that should line up with when the cooldown value becomes non-zero, but there are likely a few edge cases when we would need to expose a bit more data. (eg. Multi-shot attacks like banshee)

Can you add a separate issue for this?

**Comment by mushroom1116** [comment]
@davechurchill My recent work uses `weapon_cooldown` too. Maybe you can detect `attack` by whether the current frame `cooldown` is bigger than last frame `cooldown`. When the `cooldown` is 0, you can send `attack` command again.
