### ISSUE TITLE
Civetweb failing to compile due to pointers<->int conversions

### ISSUE THREAD

**Issue by Proch92** [Blizzard/s2client-api#108]
Hello,
i'm on linux 64bit and i'm trying to build the api.

GCC 7.1.1
Target: x86_64-pc-linux-gnu

After the steps provided in the docs

> cd build
> cmake ../

the make command fails at building civetweb. Here's the error:
```
/home/proch/dev/sc2ai/s2client-api/contrib/civetweb/src/civetweb.c: In function ‘event_create’:
/home/proch/dev/sc2ai/s2client-api/contrib/civetweb/src/civetweb.c:2425:9: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  return (void *)ret;
         ^
/home/proch/dev/sc2ai/s2client-api/contrib/civetweb/src/civetweb.c: In function ‘event_wait’:
/home/proch/dev/sc2ai/s2client-api/contrib/civetweb/src/civetweb.c:2433:20: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  int s = (int)read((int)eventhdl, &u, sizeof(u));
                    ^
/home/proch/dev/sc2ai/s2client-api/contrib/civetweb/src/civetweb.c: In function ‘event_signal’:
/home/proch/dev/sc2ai/s2client-api/contrib/civetweb/src/civetweb.c:2447:21: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  int s = (int)write((int)eventhdl, &u, sizeof(u));
                     ^
/home/proch/dev/sc2ai/s2client-api/contrib/civetweb/src/civetweb.c: In function ‘event_destroy’:
/home/proch/dev/sc2ai/s2client-api/contrib/civetweb/src/civetweb.c:2459:8: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  close((int)eventhdl);
        ^
```
Can someone point me in the right direction?

Thanks

**Comment by mejan** [comment]
Yea I got the same problem. But the error is not in the "s2client-api" it is in the submodule civetweb (which they change on 22 Aug) from a oder version. I will check now if I can pull a older version before they changed.

**Comment by KevinCalderone** [comment]
We are using a slightly modified version of civetweb v1.9.1.

Do you get the same error if you build the latest master of civetweb?
https://github.com/civetweb/civetweb

Maybe they have a fix we can pull in. Otherwise we may need to ask them to look into it.

**Comment by kuzi117** [comment]
I'm getting the error too now, and I think the lines in question are from a commit about a year old. Master builds fine for me.

**Comment by KevinCalderone** [comment]
Seems like they fixed it recently:
https://github.com/civetweb/civetweb/commit/c6fbe01f68d9e0975b0c0296baf902873e2eb792

If that does fix it, we could cherry-pick that commit onto our fork. We have avoiding using their latest master as it is unclear how stable it is since they haven't made a new release tag for awhile.

**Comment by wizzup** [comment]
civetweb/civetweb@c6fbe01 didn't work for me. same error with different location

    $ make                                           
    Scanning dependencies of target c-library
    [  1%] Building C object contrib/civetweb/src/CMakeFiles/c-library.dir/civetweb.c.o
    /home/wizzup/works/beta_projects/starcraft2/s2client-api/contrib/civetweb/src/civetweb.c: In function ‘event_create’:
    /home/wizzup/works/beta_projects/starcraft2/s2client-api/contrib/civetweb/src/civetweb.c:2428:9: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
      ret = (void *)evhdl;
            ^
    /home/wizzup/works/beta_projects/starcraft2/s2client-api/contrib/civetweb/src/civetweb.c: In function ‘event_wait’:
    /home/wizzup/works/beta_projects/starcraft2/s2client-api/contrib/civetweb/src/civetweb.c:2449:11: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
      evhdl = (int)eventhdl;
              ^
    /home/wizzup/works/beta_projects/starcraft2/s2client-api/contrib/civetweb/src/civetweb.c: In function ‘event_signal’:
    /home/wizzup/works/beta_projects/starcraft2/s2client-api/contrib/civetweb/src/civetweb.c:2475:11: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
      evhdl = (int)eventhdl;
              ^
    /home/wizzup/works/beta_projects/starcraft2/s2client-api/contrib/civetweb/src/civetweb.c: In function ‘event_destroy’:
    /home/wizzup/works/beta_projects/starcraft2/s2client-api/contrib/civetweb/src/civetweb.c:2499:11: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
      evhdl = (int)eventhdl;
              ^
    cc1: all warnings being treated as errors
    make[2]: *** [contrib/civetweb/src/CMakeFiles/c-library.dir/build.make:63: contrib/civetweb/src/CMakeFiles/c-library.dir/civetweb.c.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:105: contrib/civetweb/src/CMakeFiles/c-library.dir/all] Error 2
    make: *** [Makefile:152: all] Error 2

this is how I patch, I am on origin/master branch inside `contrib/civetweb`

    $ git rev-parse HEAD
    73303c4562d3ea5922e65a543d55233fc0d1f747

    $ curl https://github.com/civetweb/civetweb/commit/c6fbe01f68d9e0975b0c0296baf902873e2eb792.diff | patch -p1                                                                                           
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                    
                                    Dload  Upload   Total   Spent    Left  Speed                      
    100  1895    0  1895    0     0   1895      0 --:--:--  0:00:01 --:--:--  1321                     
    patching file src/civetweb.c

**Comment by Proch92** [comment]
Yeah they """fixed""" it.

Too bad the compiler doesn't know the bad cast is inside a
`if (sizeof(int) == sizeof(void *)) {`
condition. so he just throws the error again

**Comment by KevinCalderone** [comment]
That seems to be how it is on their latest master. I am confused then by why kuzi says their master build fine. Did they have some later commit where they suppress this warning?

**Comment by Proch92** [comment]
Yeah i don't know either. 
Also, i built it just fine too. i merged the two masters (civetweb's and yours) and successfully compiled the whole api.

**Comment by kuzi117** [comment]
@Proch92 That's sort of incorrect. It does understand that it's inside an if, and since size_of is a compile time operator it can understand that code inside of it can become unreachable code. It seems like clang is the only one to emit a warning about it though.

@KevinCalderone [This is the commit that fixes it.](https://github.com/civetweb/civetweb/commit/026ffe71). It pushes diagnostics to ignore those warnings, and in the case of clang, ignore unreachable code. I glanced over the rest of it and it seems to be mostly just formatting fixes.

**Comment by KevinCalderone** [comment]
It looks like @jrepp committed the fix: https://github.com/KevinCalderone/civetweb/commit/ba9c16f31304221386c179e948cad6789e4f4623

Also this issue seemed to start happening because our civetweb submodule got messed up briefly and we pulled in a bunch of new civetweb changes that we hadn't tested. That should all be reverted now too.

Can you please retest, and reopen this issue if it is still occurring for you?

**Comment by Proch92** [comment]
Nothing to reopen ;)
I just tested it on arch, gcc 7.1.1
All went smooth
