### ISSUE TITLE
tutorial.cc isn't what is described

### ISSUE THREAD

**Issue by Skarlso** [Blizzard/s2client-api#111]
So, the startup guid says this:

>Open the file examples/tutorial.cc, this is where you'll be adding your code. It is already setup with the necessary include paths and links the api.

The said cc is this:

```c++
int main(int /*argc*/, char* /*argv*/[]) {
    return 0;
}
```

I feel like it's missing a couple of things. :P

**Comment by kuzi117** [comment]
Are you trying to say it's missing include paths and links? I think it's taking about that cmake is already set up to compile it correctly. That is, it has your include paths set up and links the correct API targets against the tutorial.

**Comment by Skarlso** [comment]
Oooh, I see. The linker is setup to create the executable and things like that. I misunderstood that part than. Thanks.
