### ISSUE TITLE
Expose training/research times for units and upgrades

### ISSUE THREAD

**Issue by Sand1929** [Blizzard/s2client-api#112]
Right now, we have `build_progress` for units. However, it would be nice to know how long it takes to train/research a unit/upgrade, since `build_progress` is only a number between 0 and 1.

**Comment by davechurchill** [comment]
This is already done AFAIK and will be in the next patch

**Comment by AnthonyBrunasso** [comment]
https://github.com/Blizzard/s2client-proto/blob/blizzard_internal/s2clientprotocol/data.proto

See build_time and research_time. Thanks Dave!
