### ISSUE TITLE
[Help]Some Questions

### ISSUE THREAD

**Issue by azshalasa** [Blizzard/s2client-api#116]
Hello everyone,

Since i start on tutorials and already completed it, i was wondering how the Machine Learning some thing, i mean i feel like code a bot (similiar with Tibia #C bots), not a self learning code.

We need to set everything up,

build x svcs
if there's 16svcs stop produce.
build barracks
build factory
build x marines, 

My question is how the machine learning what it should do beyond my code, i mean if my oponnet has a lings army, the best counter with T is MMM ( medievac, marine, maraudra) how it learns how many units it need to counter oponnet, how it learn about de decisions if i didn't put it on my code, if i didn't set on my code to build exaclty 16 SVC's , how bot will learn to build just the necessary SVC ?

**Comment by alkurbatov** [comment]
Hi, @azshalasa 
I believe the machine learning question gets out of scope of the documentation in this repo. Also it is more common to use Python for such tasks not C++.

Please take a look at deepminds repo which is probably what you are searching for:
 https://github.com/deepmind/pysc2

**Comment by tylerwhipple** [comment]
I am not an expert at all.... but my thoughts. 

You need to define a way to reward function, at the highest level it will be a 0 or 1 on whether the bot won or lost. Or another proposed reward function is the "Starcraft Score" at the end of the game, which awards you points for mining minerals/building units/etc.

You will build a bot that performs actions, generates a score and learns based off this.

I attached the paper since I cant explain that well.
https://arxiv.org/pdf/1708.04782.pdf

**Comment by azshalasa** [comment]
Hello @alkurbatov and @tylerwhipple  tx for your attention and fast reply.

So i think i misunderstood the definiton about the tools, i would apreciate a help to define that tools.

s2client-api  is a bot wich i can easly code with c++ ? 
pysc2 is another complety different tool with a real machine learning, not a bot. 
i was thinking PySC2 was just a bias to identify the things on the game.

i spend my last 12H reading all documentations and i feel like i dont know nothing.

**Comment by alkurbatov** [comment]
From my point of view this API allows to create a script bot e.g. like the one below:
https://github.com/davechurchill/commandcenter

I don't know much regarding deepmind's project but it looks like a project built using this api in order t allow to create another bot which takes decision based on some algorithm and learning. You can do some machine learning in C++ too but Python has some nice frameworks and in general simpler to code. That is the readon why it is more wide spread among datascience tasks.

**Comment by KevinCalderone** [comment]
Closing this as it doesn't seem like there any more questions here specific to the C++ API.

If you want to discuss more machine learning ideas, here are a few places you can try:
Forums: https://us.battle.net/forums/en/sc2/22814033/
Unofficial Facebook Group: https://www.facebook.com/groups/969196249883813/
Unofficial Discord: https://discordapp.com/channels/350289306763657218/350289306763657220
