### ISSUE TITLE
Camera control features

### ISSUE THREAD

**Issue by N00byEdge** [Blizzard/s2client-api#118]
Will there be controls for the ingame camera? It could be used to auto-spectate games without having to interact with it, simple camera control script could let you see what happens in really fast games.

**Comment by KevinCalderone** [comment]
There is a DebugInterface::DebugMoveCamera. Is that what you are looking for?

The more flexible way would be to be able to join a game as an observer. I'd like to add this but not sure what the timeline is for that.

**Comment by N00byEdge** [comment]
Sorry I just realized there was a lot of ActionSpatialCameraMove in the file .pb.h, or can the DebugInterface be used outside of debug builds? Never thought of that.
