### ISSUE TITLE
Can't compile CommandCenter with last precompiled libs

### ISSUE THREAD

**Issue by richoux** [Blizzard/s2client-api#124]
While trying to compile CommandCenter either in debug or release mode, I have got massive errors with multiple C/C++ Optimizing Compiler crashes. I could compile CommandCenter with the previous precompiled libs (but couldn't run the executable though).

**Comment by KevinCalderone** [comment]
We just updated the precompiled lib package to 3.17. Can you redownload it and test it again?

**Comment by KevinCalderone** [comment]
Closing this to keep out issues clean. If you retest and find it is still broken, feel free to reopen this.
