### ISSUE TITLE
Chaining unit orders

### ISSUE THREAD

**Issue by noorus** [Blizzard/s2client-api#138]
As far as I can tell, there's currently no way in the protocol/API to give a unit an array of commands at once, nor append more later. However the unit's order list (vector) with multiple commands is retrievable via the observation interface if you give chained commands to a unit yourself ingame.

Will chaining unit orders via the API be supported in the (near) future? It would simplify bot development substantially, I find.

**Comment by KevinCalderone** [comment]
There is a way to do it in the underlying protocol (ActionRawUnitCommand::queue_command), but it looks like we aren't exposing it currently in the C++ interface. We should probably add it as an optional parameter to the UnitCommand functions.

**Comment by AnthonyBrunasso** [comment]
Added in: 21a516a0641b468bf17e9e6cb413c694e38c69ac
