### ISSUE TITLE
Tutorial code doesn't compile

### ISSUE THREAD

**Issue by KevinCalderone** [Blizzard/s2client-api#140]
Much of the interface was recently changed to take unit pointers rather than tags. The code in the tutorials needs to be updated for this change.

**Comment by AnthonyBrunasso** [comment]
That was actually part of my local change list. I must have forgotten to add them to the commit. I can get it in on Monday.

**Comment by confessore** [comment]
I created a pull request with the changes. let me know what you think

**Comment by AnthonyBrunasso** [comment]
Thanks for fixing this for us @confessore! 

5f9723b30d7191cfcc15b8b38e2b8fbba8ed45b2
