### ISSUE TITLE
TestFastRestartSinglePlayer works slowly on Linux virtual machines

### ISSUE THREAD

**Issue by TommyTran93** [Blizzard/s2client-api#15]

**Comment by kuzi117** [comment]
It runs slowly for me running native Ubuntu 16.04 as well. It went through 2/10 iterations (killed on 3) before I stopped running it. Seemed like 20 minutes at least.

**Comment by AnthonyBrunasso** [comment]
I know there is an issue on Ubuntu with tcp_nodelay not being set in the civetweb library. We've had to hack around this before. I can modify our fork and we can retest on linux. It should help, I think the round trip time between library and SC2 is like 40ms without it and a tenth of a millisecond with it.

I'll let you know when I update our fork.

**Comment by sihuaiwei** [comment]
I cmake s2client-api on linux but the erros that :
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/libcivetweb.a
-- Up-to-date: /usr/local/include/civetweb.h
CMake Error at contrib/civetweb/src/cmake_install.cmake:50 (file):
  file INSTALL cannot find
  "/home/sihuaiwei/桌面/git/s2client-api/build/bin/civetweb".
Call Stack (most recent call first):
  contrib/civetweb/cmake_install.cmake:37 (include)
  cmake_install.cmake:37 (include)
how to slove it

**Comment by AnthonyBrunasso** [comment]
This should be fixed now, I updated our civetweb fork, please reopen if you are still seeing long waits.
