### ISSUE TITLE
Expose unit prerequisites

### ISSUE THREAD

**Issue by KevinCalderone** [Blizzard/s2client-api#16]
eg. A Barracks requires a supply depot. An infestor requires an infestation pit.

There may be cases where something requires an upgrade?

In the short term, possible hard code a map of all these dependencies.

**Comment by kuzi117** [comment]
For something requiring upgrades example, Zerg Melee Attacks Level 2 requires a Lair and Zerg Melee Attacks Level 1. Or morphing dropper-lords requires Ventral Sacs, which is actually probably the closest thing to what you meant.

Could this be extended to abilities map to the upgrade required for them? E.g. storm or neural parasite?

**Comment by KevinCalderone** [comment]
Structure/Unit prerequisites has been added and will be out in the 3.17 patch (#103).

**Comment by AnthonyBrunasso** [comment]
This is now live. See UnitTypeData::tech_requirement
