### ISSUE TITLE
Request: GameInfo.all_start_locations

### ISSUE THREAD

**Issue by davechurchill** [Blizzard/s2client-api#161]
Right now we have access to Observation()->GetGameInfo().enemy_start_locations

Would it be possible to have an additional vector which included all start locations?

A common use case is to loop over all start locations on the map to do some strategic logic, but right now they are separated into the vector of possible enemy start locations and a separate listing for the player's start location, which makes this iteration a little annoying to set up.

**Comment by AnthonyBrunasso** [comment]
Added in #162
