### ISSUE TITLE
Implement Realtime for replays

### ISSUE THREAD

**Issue by Itja** [Blizzard/s2client-api#167]
As of now, after setting `coordinator->SetRealtime(true);` loading a replay leads to [this block of code](https://github.com/Blizzard/s2client-api/blob/master/src/sc2api/sc2_coordinator.cc#L690) in the Coordinator being reached, yielding an `assert(0);` beneath a `//TODO`.

We're trying to stream games automatically, and for this, realtime replay would be a quite necessary feature. It would be great if this could be implemented.

**Comment by AnthonyBrunasso** [comment]
Ah yes, sorry about that. We will get to that soon.

**Comment by AnthonyBrunasso** [comment]
This will be available when our next patch releases. It required a game change to support.

**Comment by Itja** [comment]
Thanks a lot!

**Comment by jkantr** [comment]
@AnthonyBrunasso Sorry to ping on a closed thread... but this seems to.. not work (see https://github.com/Blizzard/s2client-api/issues/274#issuecomment-447925343). Can you confirm that this patch was completed and what version it appeared in?
