### ISSUE TITLE
TERRAN_COMMANDCENTER data is not filled on game start

### ISSUE THREAD

**Issue by alkurbatov** [Blizzard/s2client-api#168]
I have the following code very similar to the tutorial. The code must limit the number of SCVs built for a particular command center:

```c++
virtual void OnUnitIdle(const sc2::Unit* unit) final {
    switch (unit->unit_type.ToType()) {
        case sc2::UNIT_TYPEID::TERRAN_COMMANDCENTER: {
            if (unit->assigned_harvesters < unit->ideal_harvesters)
                Actions()->UnitCommand(unit, sc2::ABILITY_ID::TRAIN_SCV);
            break;
        }
....
        default: {
            break;
        }
    }
}
```

However when the game starts only starts and OnUnitIdle is triggered the TERRAN_COMMANDCENTER unit structure is not filled properly, e.g.:
```
    frame #0: 0x000000010000bac3 Suvorov`Bot::OnUnitIdle(this=0x00007fff5fbff5a0, unit=0x0000000102e08c10) + 83 at Bot.h:38
   35   virtual void OnUnitIdle(const sc2::Unit* unit) final {
   36       switch (unit->unit_type.ToType()) {
   37           case sc2::UNIT_TYPEID::TERRAN_COMMANDCENTER: {
-> 38               if (unit->assigned_harvesters < unit->ideal_harvesters)
   39                   Actions()->UnitCommand(unit, sc2::ABILITY_ID::TRAIN_SCV);
   40               break;
   41           }
(lldb) p *unit
(const sc2::Unit) $0 = {
  display_type = Visible
  alliance = Self
  tag = 4348968961
  unit_type = (type_id_ = 18)
  owner = 1
  pos = (x = 26.5, y = 137.5, z = 11.9960938)
  facing = 3.92529726
  radius = 2.75
  build_progress = 1
  cloak = NotCloaked
  detect_range = 0
  radar_range = 0
  is_selected = false
  is_on_screen = true
  is_blip = false
  health = 1500
  health_max = 1500
  shield = 0
  shield_max = 0
  energy = 0
  energy_max = 0
  mineral_contents = 0
  vespene_contents = 0
  is_flying = false
  is_burrowed = false
  weapon_cooldown = 0
  orders = size=0 {}
  add_on_tag = 0
  passengers = size=0 {}
  cargo_space_taken = 0
  cargo_space_max = 0
  assigned_harvesters = 0
  ideal_harvesters = 0
  engaged_target_tag = 0
  buffs = size=0 {}
  is_powered = false
  is_alive = true
  last_seen_game_loop = 0
}
```

All the data are in place on the next 'OnUnitIdle' so I can check the limits with the following workaround:

```c++
virtual void OnUnitIdle(const sc2::Unit* unit) final {
    switch (unit->unit_type.ToType()) {
        case sc2::UNIT_TYPEID::TERRAN_COMMANDCENTER: {
            if (unit->assigned_harvesters == 0 ||
                    unit->assigned_harvesters < unit->ideal_harvesters) {
                Actions()->UnitCommand(unit, sc2::ABILITY_ID::TRAIN_SCV);
            }

            break;
        }
....
        default: {
            break;
        }
    }
}
```

Is such behaviour intended? That looks like a race (the game info is not fully initialised at the moment of the event).

**Comment by davechurchill** [comment]
No units have been given commands yet on onStart(), I think you have to wait until an onStep() has been called

**Comment by alkurbatov** [comment]
The main problem here is that ideal_harvesters is zero which us not related to the number of units if I not mistaken. Another problem: if you write the bot in that way the idle callback will be fired only once for the command center i.e. when there are only zeroes.

**Comment by davechurchill** [comment]
I believe ideal_harvesters is based on the number of minerals near the depot, so it cannot be determined before OnStart() has been called. You still probably have to wait until the first OnStep

**Comment by alkurbatov** [comment]
>No units have been given commands yet on onStart(), I think you have to wait until an onStep() has been called
Could be because onStep is triggered after OnUnitIdle when game starts. This is a minor issue anyway.

**Comment by AnthonyBrunasso** [comment]
OnGameStart should be issued before any of the other events. This does seem wrong to me, it could be that the observation gathered at game loop 0 just doesn't have the necessary data for ideal_harvesters. I can look into this one today. I feel like assigned_harvesters might take a game loop to show up but I would have thought ideal_harvesters would be immediately filled out.

**Comment by alkurbatov** [comment]
I’ve checked it in the debugger, the current event order is: 1 - onGameStart, 2 - onUnitIdle, 3 - onStep. That looks like a correct order.

**Comment by AnthonyBrunasso** [comment]
This turned out to be a bug in an engine. Essentially these values were not properly set on game loop 0. I've added the necessary fix and this code should work as you expect it for both assigned_harvesters and ideal_harvesters for game loop 0 after our next patch goes live.

**Comment by alkurbatov** [comment]
Thank you! Glad to hear.
