### ISSUE TITLE
How to get the outcome of a match? 

### ISSUE THREAD

**Issue by yt4766269** [Blizzard/s2client-api#169]
I am developing a StarCraft 2 bot Ladder platform based on the SC2 api. However, I cannot find the api of getting the match result. How can I get the outcome of a match?
Thanks.

**Comment by AnthonyBrunasso** [comment]
c840e10289e17778649e32270e3b8f5ca62dd3d4

Call Observation()->GetResults() in OnGameEnd(). Thanks for bringing this up!
