### ISSUE TITLE
libsc2protocol linking errors under Ubuntu 16.04

### ISSUE THREAD

**Issue by alkurbatov** [Blizzard/s2client-api#170]
I have the following Ubuntu 16.04.3 LTS Docker Container:
https://github.com/alkurbatov/stash/blob/master/work/docker/ubuntu-dev/Dockerfile

I try to build the API and commandcenter in this Container as it is described here:
https://github.com/davechurchill/commandcenter#developer-install--compile-instructions-linux-and-os-x

However during linking stage I got a lot protobuf linking errors from libsc2protocol library, e.g.:
```
/opt/local/lib/sc2api/libsc2protocol.a(data.pb.cc.o):(.rodata._ZTIN14SC2APIProtocol11DamageBonusE[_ZTIN14SC2APIProtocol11DamageBonusE]+0x10): more undefined references to `typeinfo for google::protobuf::Message' follow
```

The question is: what goes wrong here? The same order of actions works perfectly on OS X but not on Linux.

**Comment by AnthonyBrunasso** [comment]
This is surprising because we build the API under Ubuntu 16.04.2. Have you followed our build instructions from the documents section?

**Comment by alkurbatov** [comment]
I did.

The trick is that everything is ok with the API. The problem arise when we want to link the bot with libsc2protocol.

**Comment by AnthonyBrunasso** [comment]
I see, so  you are linking the protocol in a separate project?

It seems like it can't find one of protobuf's types? Do you have the libprotobuf.a?

**Comment by alkurbatov** [comment]
>I see, so you are linking the protocol in a separate project?

Yes.

Libprotobuf.a is in place. The linker command is:
‘’’
/usr/bin/c++   -Wall -Wextra   CMakeFiles/CommandCenter.dir/BuildOrderQueue.cpp.o CMakeFiles/CommandCenter.dir/MapTools.cpp.o CMakeFiles/CommandCenter.dir/WorkerData.cpp.o CMakeFiles/CommandCenter.dir/BaseLocation.cpp.o CMakeFiles/CommandCenter.dir/BuildingData.cpp.o CMakeFiles/CommandCenter.dir/SquadOrder.cpp.o CMakeFiles/CommandCenter.dir/MicroManager.cpp.o CMakeFiles/CommandCenter.dir/RangedManager.cpp.o CMakeFiles/CommandCenter.dir/BuildingPlacer.cpp.o CMakeFiles/CommandCenter.dir/MeleeManager.cpp.o CMakeFiles/CommandCenter.dir/BuildOrder.cpp.o CMakeFiles/CommandCenter.dir/CCBot.cpp.o CMakeFiles/CommandCenter.dir/Util.cpp.o CMakeFiles/CommandCenter.dir/BotAssert.cpp.o CMakeFiles/CommandCenter.dir/JSONTools.cpp.o CMakeFiles/CommandCenter.dir/Squad.cpp.o CMakeFiles/CommandCenter.dir/UnitType.cpp.o CMakeFiles/CommandCenter.dir/UnitInfoManager.cpp.o CMakeFiles/CommandCenter.dir/BaseLocationManager.cpp.o CMakeFiles/CommandCenter.dir/DistanceMap.cpp.o CMakeFiles/CommandCenter.dir/StrategyManager.cpp.o CMakeFiles/CommandCenter.dir/Unit.cpp.o CMakeFiles/CommandCenter.dir/main.cpp.o CMakeFiles/CommandCenter.dir/BuildingManager.cpp.o CMakeFiles/CommandCenter.dir/GameCommander.cpp.o CMakeFiles/CommandCenter.dir/ScoutManager.cpp.o CMakeFiles/CommandCenter.dir/SquadData.cpp.o CMakeFiles/CommandCenter.dir/Building.cpp.o CMakeFiles/CommandCenter.dir/ProductionManager.cpp.o CMakeFiles/CommandCenter.dir/BotConfig.cpp.o CMakeFiles/CommandCenter.dir/TechTree.cpp.o CMakeFiles/CommandCenter.dir/WorkerManager.cpp.o CMakeFiles/CommandCenter.dir/CombatCommander.cpp.o CMakeFiles/CommandCenter.dir/UnitData.cpp.o CMakeFiles/CommandCenter.dir/MetaType.cpp.o  -o ../bin/CommandCenter -rdynamic /opt/local/lib/sc2api/libcivetweb.a /opt/local/lib/sc2api/libprotobuf.a /opt/local/lib/sc2api/libsc2api.a /opt/local/lib/sc2api/libsc2lib.a /opt/local/lib/sc2api/libsc2protocol.a /opt/local/lib/sc2api/libsc2utils.a
‘’’

**Comment by AnthonyBrunasso** [comment]
Here is the relevant portion when we are linking our examples:

-rdynamic ../bin/libsc2api.a ../bin/libsc2lib.a ../bin/libsc2utils.a ../bin/libsc2api.a ../bin/libsc2protocol.a ../bin/libprotobuf.a /usr/lib/x86_64-linux-gnu/libz.so ../bin/libcivetweb.a -lpthread -ldl

Two things I've noticed -

1. libsc2protocol comes before libprotobuf when linking. I believe the order matters here if you're using gcc. 
2. -lpthread and -ldl though I don't think that'd make a difference.

**Comment by alkurbatov** [comment]
Thank you! The order matters, I've totally forgot about it. Shame on me :(

>-lpthread and -ldl though I don't think that'd make a difference.
These libraries are needed too.

I'll prepare the patch for commandcenter. The issue is closed.
