### ISSUE TITLE
Can't go through multi-players mode with Feature Layers map.

### ISSUE THREAD

**Issue by cumttang** [Blizzard/s2client-api#177]
**These are the kernel codes.**
{
       coordinator.SetFeatureLayers(sc2::FeatureLayerSettings());
	coordinator.SetMultithreaded(true);
	coordinator.SetStepSize(1);
	coordinator.SetRealtime(false);

	Bot bot1;
	Bot bot2;
    coordinator.SetParticipants({
        CreateParticipant(Race::Terran, &bot1),
		CreateParticipant(Race::Terran,  &bot2)
    });

    coordinator.LaunchStarcraft();
    coordinator.StartGame(sc2::kMapBelShirVestigeLE);

}

**When I ran the codes, the problem occured:**
{
Waiting for the JoinGame response.
WaitJoinGame finished successfully.
Waiting for the JoinGame response.
WaitJoinGame finished successfully.
While waiting for ResponseObservation received an error.
Error: Not in a game

Error in returning observation:
The main response is of type: 0
There is no ResponseObservation/message!
Error string: Not in a game

While waiting for ResponseObservation received an error.
Error: Not in a game

Error in returning observation:
The main response is of type: 0
There is no ResponseObservation/message!
Error string: Not in a game
}

**However, when I comment on "coordinator.SetFeatureLayers(sc2::FeatureLayerSettings());". It will work. But I wanna use the Feature Layer Map. So, how can I solve the problem?**

**Comment by KevinCalderone** [comment]
Sorry the error message there is pretty unclear. Currently feature layers aren't supported for multiplayer games. However, this will become available in our next patch. Please reopen this if it still doesn't work in the next patch.
