### ISSUE TITLE
Any way to run the simulation at normal game speed?

### ISSUE THREAD

**Issue by edwinsaunders** [Blizzard/s2client-api#179]
I tried using coordinator.SetStepSize(), but it only takes int values, and the default value of 1 is already much faster than a normal game.

**Comment by alkurbatov** [comment]
I used the following workaround:
```c++
    while (coordinator.Update()) {
        // Slow down game speed for better look & feel while making experiments.
        sc2::SleepFor(15);
    }
```

It seems that we have no other way.

**Comment by KevinCalderone** [comment]
Another option is:
```C++
coordinator.SetRealtime(true);
```

However this also has the effect where a variable number of GameLoops may pass between calls to your OnStep depending on how slow your logic is. If this is undesirable I suggest alkurbatov's solution.

**Comment by herodrigues** [comment]
@KevinCalderone, @edwinsaunders' solution works, but keep in mind that you have to include manage_process header though.

`#include <sc2utils/sc2_manage_process.h>`
