### ISSUE TITLE
Drones that morph to buildings are never marked as dead

### ISSUE THREAD

**Issue by noorus** [Blizzard/s2client-api#180]
This is quite a serious issue/oversight:
As zerg drones become buildings, the created building is a new unit, but the existing drone is never marked as destroyed/dead. It becomes impossible to know which drones still exist and which do not. Unless I'm missing something, but I don't see anything in the unit data that I could use to tell when this has happened.

**Comment by AnthonyBrunasso** [comment]
Oh, that is incredibly bad. This is likely an issue introduced with the unit pointer change. Fixing this will be my highest priority, thank for bringing it to our attention.

**Comment by AnthonyBrunasso** [comment]
I fixed this but it will unfortunately take until December to become available. It required a game side change and that will be the closest patch it can come out in.

In the meantime I recommend using a call to GetUnits() each OnStep to get drones. This works as it will only return units that came in during the last call to GetObservation.

**Comment by noorus** [comment]
Alright, good recommendation. I should've noted that this also affects larvae, but I assume the fix probably patched all similar scenarios.
Thanks!
