### ISSUE TITLE
stropts.h not found

### ISSUE THREAD

**Issue by jdellithorpe** [Blizzard/s2client-api#184]
Hi all,

After reading around a bit, it appears that stropts.h is a header file for the STREAMS interface, which is no longer supported by modern linux distributions. This header file, however, is used in `./sc2utils/sc2_manage_process.cc` thus resulting in:

`s2client-api/src/sc2utils/sc2_manage_process.cc:55:21: fatal error: stropts.h: No such file or directory`

Is this header file necessary?

**Comment by herodrigues** [comment]
How did you get to this error? Can you post your code?

**Comment by AnthonyBrunasso** [comment]
Hi there! I removed the header in 6d0f6138f906ff7c661f25dee47fad7416a2b7c6.

Seemed fine without it. Thanks for letting us know!

**Comment by jdellithorpe** [comment]
@AnthonyBrunasso Thanks!

@herodrigues I am running on Amazon Linux AMI 2017.09.0.20170930 x86_64 HVM GP2 which appears to be based on kernel release 4.9:

```
$ uname --kernel-release
4.9.51-10.52.amzn1.x86_64
```

**Comment by herodrigues** [comment]
@jdellithorpe if it's not supported and not used, so @AnthonyBrunasso is right about removing it.
I use Arch Linux and didn't get that error.
