### ISSUE TITLE
Following documentation results in failure

### ISSUE THREAD

**Issue by ccarterc** [Blizzard/s2client-api#200]
The build works just fine on Ubuntu, but none of the necessary dependencies are available for the tutorial script.  `#include <sc2api/sc2_api.h>` cannot be found.

**Comment by Patrick-Edouard** [comment]
You made a new c++ file ? If so, ensure its CMakeFile ´´'target_link_libraries''' is set properly and references sc2api.

**Comment by AnthonyBrunasso** [comment]
I just tried this and it seemed to work fine. The tutorial project should already be set up with the necessary include paths.

**Comment by ccarterc** [comment]
If you want to understand how the documentation results in failure, start with a fresh Ubuntu install and then follow the instructions precisely using the prebuilt binary method.  Dependencies are missing, configurations are incorrect.

As a follow up, I tried the tutorial on Windows as well.  For Windows 10...
Followed build instructions with cmake after cloning repo just fine.
Followed tutorial1.md directions to the point of first build which fails (submitted a PR for a minor correction in docs).  But ultimately end up here:
`Unable to start program ...\build\x64\Release\ALL_BUILD     Access is denied`

**Comment by ccarterc** [comment]
By default the wrong project is built when loaded with visual studio.  Once you manually trigger a build on the right sub-folder, it will build correctly.  I'll check the docs again and submit a pr if they can be clarified at all.
