### ISSUE TITLE
Query()->GetAbilitiesForUnit(unit) for Engineering Bay shows no abilities

### ISSUE THREAD

**Issue by Archiatrus** [Blizzard/s2client-api#215]
Hi,

as the title says: Query()->GetAbilitiesForUnit(unit) for Engineering Bay gives back an empty vector.

Regards

**Comment by DonThompson** [comment]
FYI, I tested this out and had no problems.  The list of available abilities was always update and correct even as upgrades were performed.

**Comment by Archiatrus** [comment]
Thank you for testing it.

That is weird. Just now I tested it by calling repeatedly (but not every OnStep)

`
    std::vector<sc2::AvailableAbility> abilities = m_bot.Query()->GetAbilitiesForUnit(unit).abilities;
    abilityCount[abilities.size()]+=1;
`

From when the engineering bay was finished until a while after +1/+1 is done and a armory is finished but no new upgrade started. I would expect a lot for 5 (when one or no upgrade gets researched) and a few for 4 (when one upgrade is done, one gets researched but no armory is finished). Instead I get:
abilityCount[0] = 859
abilityCount[1] = 2686 
abilityCount[2] = 101
abilityCount[3] = 104
abilityCount[4] = 141
abilityCount[5] = 0
So it is indeed not always empty but it is also not correct. At least for me... From when is your sc2api source and when did you install SC2?

**Comment by DonThompson** [comment]
I'm linking against the precompiled libraries (they're linked in the main readme at the bottom).  They appear to have been built 9/28/2017.

**Comment by DonThompson** [comment]
Figured it out -- the abilities take into account resource requirements.  If you don't have enough gas, then you can't build anything.  Here's the steps I took to repro with latest code.


Repro attempt steps:
- pull latest code (follow readme instructions)
- set examples\bot_simple as the startup project
- add the following line as a public member of FooBot
int32_t abilityCount[10];
- modify bot_simple.cc OnStep() function to be the following:
virtual void OnStep() final {
        sc2::Units ebays = Observation()->GetUnits(sc2::IsUnit(sc2::UNIT_TYPEID::TERRAN_ENGINEERINGBAY));
        for (const sc2::Unit* ebay : ebays) {
            std::vector<sc2::AvailableAbility> abilities = Query()->GetAbilitiesForUnit(ebay).abilities; 
            abilityCount[abilities.size()] += 1;
        }
    };

- Run the game.
- build ebay manually, no other buildings
- wait a few moments and check the values via breakpoint

while the ebay is building, the count is always 2 (halt, cancel)
after completion, the size is always 0 (UI shows 5 buttons)
built a refinery.  as soon as i hit 100 gas, the ability count raised to 4 (structure armor requires 150 gas)

**Comment by Archiatrus** [comment]
Thanks a lot. For some reason I did not consider resources as requirement.
