### ISSUE TITLE
GameSettings' map name always get overwritten

### ISSUE THREAD

**Issue by T-Jin** [Blizzard/s2client-api#231]
Starting off with the given examples, passing in map name never seemed to work.

Observations:

There seems to be no public getter to retrieve the map name inside GameSetting of the coordinator.
StartGame() and CreateGame() both takes const string& as param. Use empty string as default argument. Will always overwrite the map name with the passed in value.
With these two combined, I'm in a funny scenario. After passing in a map name through command-line argument, I can't read the map name from the coordinator and use it as param for Start/CreateGame().

Examples only work b/c map path are hard-coded everywhere.

Perhaps inside Start/CreateGame(), check for empty map name. If it is empty, use the map name inside GameSettings (as oppose to always overwrite the map name)?

**Comment by herodrigues** [comment]
@T-Jin, I see your PR was merged.

Could you please close this issue? Let's clean up the issues list a bit.
