### ISSUE TITLE
missing cmake INSTALL target

### ISSUE THREAD

**Issue by T-Jin** [Blizzard/s2client-api#232]
Cmake INSTALL target doesn't actually install built sc2api libs to CMAKE_INSTALL_PREFIX location. 
Dependent libs (like protobuf and civetweb) does get copied over, but not sc2api.lib, ac2lib.lib, etc.

Is this intended behavior? Add the install target to cmakelist inside ./src?

Tested on win10 x64 with vs2017

**Comment by alkurbatov** [comment]
Hi @T-Jin .
It had been implemented by @kuzi117 about a month ago, see #206

**Comment by T-Jin** [comment]
Cool. Hope the fix get merged soon.
