### ISSUE TITLE
Never see CARRYHARVESTABLEVESPENEGEYSERGAS 

### ISSUE THREAD

**Issue by sdgsdfs** [Blizzard/s2client-api#241]
I'm trying to figure out how many SCVs are carrying Vespene by watching their buffs. Unfortunately they are always 271 (CARRYMINERALFIELDMINERALS). Can someone help me out?

**Comment by macattackftw** [comment]
Fun fact: when a unit emerges from a gas collector it triggers OnUnitCreated (keeps the same tag, just triggers the event). You can check the buffs then. The buff is 275. I can see it with Zerg just fine, not sure about the other races.

**Comment by sdgsdfs** [comment]
Ok, my mistake. If you look at buffs.end() there ist the current buff wich contains the CARRYHARVESTABLEVESPENEGEYSERGAS Flag...
