### ISSUE TITLE
replays bug?

### ISSUE THREAD

**Issue by ayu-mail** [Blizzard/s2client-api#242]
The following code captures the SCV production record of more than 800, in fact less than 100, testing multiple replays of a wide range, the SCV has this problem, other unit types are not.

    void OnUnitCreated(const sc2::Unit* unit)
    {
        std::cout << UnitTypeToName(unit->unit_type)  << std::endl;
    }

**Comment by macattackftw** [comment]
OnUnitCreated() is called when SCVs exit Refineries.

**Comment by ayu-mail** [comment]
Thank you very much
