### ISSUE TITLE
Link to Tutorials on Doxygen broken

### ISSUE THREAD

**Issue by FMorsbach** [Blizzard/s2client-api#244]
Hi,

on the [doxygen landing ](https://blizzard.github.io/s2client-api/) page the tutorial links are broken. 

![image](https://user-images.githubusercontent.com/15376822/37143037-3592e982-22ba-11e8-8f3a-c99955e79f01.png)

**Comment by herodrigues** [comment]
Fixed in https://github.com/Blizzard/s2client-api/pull/252.
Awaiting moderation.

Live result: http://herodrigues.me/s2client-api/
