### ISSUE TITLE
How to tell what is being built inside a Zerg Egg?

### ISSUE THREAD

**Issue by lrc374** [Blizzard/s2client-api#283]
Is there a function call to check what unit type is currently being produced by a Zerg Egg? I can't find it on my own in the API

**Comment by alkurbatov** [comment]
Hi, @lrc374 
I used the following:
```unit_->orders.front().ability_id == sc2::ABILITY_ID::TRAIN_OVERLORD```

**Comment by lrc374** [comment]
Thanks!!
