### ISSUE TITLE
test_multiplayer unable startgame

### ISSUE THREAD

**Issue by mboedigh** [Blizzard/s2client-api#312]
the test_multiplayer Launches SC2 but time out in coordinate.StartGame. 
Many things in the sc2api broken when sc2 updated itself.  I'm at Base74741. Is there a way back?

**Comment by suoni414** [comment]
I aslo met this problem. I can only find old version in linux. Did someone have better solution?

**Comment by suoni414** [comment]
Test_multiplayer successed in Version4.9.3. Long love the Blizzard!

**Comment by mboedigh** [comment]
sc2client-api/tests/all_tests TestMultiplayer is working here now too.
