### ISSUE TITLE
Compile tutorial.cc broken on Linux?

### ISSUE THREAD

**Issue by brancoliticus** [Blizzard/s2client-api#318]
My system is a Debian 9. I followed the build guide to the letter, cloning recursively but I have the same king of problems as in issue #83. If someone could help me out figure how to solve building the tutorial examples.

 Below is every command I entered and it's output starting from the git clone, towards the bottom there are the compilation commands with output after several attempts to edit files to make the compilation work:

[compiler_error_output2.txt](https://github.com/Blizzard/s2client-api/files/3502771/compiler_error_output2.txt)

**Comment by alkurbatov** [comment]
Hi @brancoliticus 
Seems that this happens because you have another version of Protobuf installed in your system.
See the following error:
`../include/sc2api/../../build/generated/s2clientprotocol/sc2api.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please`

**Comment by brancoliticus** [comment]
Yes I installed the debian protocol buffers but that wasn't when my troubles started.  Please look further back in the output I uploaded to before the installation of the debian protocol buffers. Thank you.

**Comment by alkurbatov** [comment]
Could you please point on the exact line? So far I see that you've compiled the sources successfully. As a result, the examples was compiled too (try to do from the build folder: `ls bin/tutorial`).
The following command is definitely incorrect as it requires paths to include folders and linking flags:
`g++ tutorial.cc -o /home/brancoliticus/tutorial_SC2`

**Comment by brancoliticus** [comment]
I didn't realise that the compilation of the API will also compile the examples. This clears the matter for me. Thank you for your time.
