### ISSUE TITLE
Persist units the entire game and update GetUnit and GetUnits calls to return pointers.

### ISSUE THREAD

**Issue by davechurchill** [Blizzard/s2client-api#37]
Talked to Kevin about this, it might be good for consistency, since Observation->GetUnit(tag) returns a pointer and GetUnits() return objects I find myself getting them mixed up in the bot. Having them all be pointers makes it a little more consistent, but I'm not sure if this is necessary

**Comment by AnthonyBrunasso** [comment]
I think the long term plan here is to make units persist per frame. Each call will return a pointers that you can keep around per frame with a is_dead or is_alive member in them.

This would be an interface breaking change but I think it's a good one.

**Comment by davechurchill** [comment]
When you say "persist per frame" do you mean that pointers will be valid over the course of multiple frames, or only guaranteed to be valid for a single frame? As it stands right now, I think unit pointers are potentially invalidated whenever a new unit is created.

And yes, it would require a change to anyone who has currently written code, but this would be a good change for consistency and performance, and doing it soon means that less code breaks :)

**Comment by KevinCalderone** [comment]
"persist per frame" = Unit object will stay valid for the entire game. You convinced us to make this change :)

**Comment by davechurchill** [comment]
Does this mean that internally the units will be stored in a static sized data structure so that the pointers will remain valid? If so, will that mean that there is an upper bound on the number of units that can be generated in a game?

If you put units in a std::vector for example, adding more of them will invalidate pointers when the vector is resized

**Comment by davechurchill** [comment]
That's also kind of funny, to be "persist per frame" implies they are only valid per frame, ie: for a single frame :D

**Comment by KevinCalderone** [comment]
Yes we will make sure we do it in a way that keeps the pointers valid.

**Comment by davechurchill** [comment]
Great, I think that would be a welcome change for bot programmers! Also a huge QOL boost. As you can see in the CommandCenter code, I am currently storing unit tags because of this limitation, which means that whenever I want to use the unit with the tag I need to make a call to GetUnit and then a pointer check to make sure it isn't null

**Comment by AnthonyBrunasso** [comment]
Part of this change should be updating the ActionInterface to take Unit pointers and a list of Unit pointers instead of a tag.

**Comment by davechurchill** [comment]
I think that having both tag and pointer passing in ActionInterface would be an asset

**Comment by AnthonyBrunasso** [comment]
I think we'd just like to encourage a single usage of the interface and unit handling in general. Is there a strong reason, to you, for the interface to allow for both? Assuming the change for game lasting unit pointers exist.

**Comment by AnthonyBrunasso** [comment]
This is implemented in: f56521f400a3f3d797a2a8ba3660f7e943bf7ab6
