### ISSUE TITLE
Include sc2api.pg.h error (in my bot's project file) / precompiled libs rename

### ISSUE THREAD

**Issue by davechurchill** [Blizzard/s2client-api#47]
In my bot's solution/project file, I am using the precompiled libs download to include and link against

So I am pointing my solution to the "include" folder for the includes, and the "lib" folder for the libs

The error I am getting is from line 5 of sc2_proto_interface.h, which attempts to include sc2api.pb.h, however that file is in another folder so it throws an error on compile

There are two ways to fix this:
- I could point the compiler at the include/sc2protocol/ directory as well (kind of annoying)
- Just change that line to #include "../sc2protocol/sc2api.pb.h" which breaks nothing and fixes my problem

I strongly suggest this change, as it removes the need to include multiple header folders

**Comment by AnthonyBrunasso** [comment]
We fixed this by putting the generated files in include/ of the prebuilt solution. Thanks Dave!
