### ISSUE TITLE
coordinator.Update() Doc Comment wrong

### ISSUE THREAD

**Issue by mk4321** [Blizzard/s2client-api#50]
https://github.com/Blizzard/s2client-api/blob/master/include/sc2api/sc2_coordinator.h#L126

> //! \return True if the game has ended, false otherwise.
> bool Update();

for Update()...isn't the return value actually exactly the opposite (false if the game has ended)?

**Comment by AnthonyBrunasso** [comment]
Yes, you are correct. I will update the docs accordingly. Thank you.

**Comment by AnthonyBrunasso** [comment]
Fixed in b6e3b1d1e88c125b4e937c8619079bb0c01e9f7e

Thank you!
