### ISSUE TITLE
PowerSource definition seems out of place

### ISSUE THREAD

**Issue by kuzi117** [Blizzard/s2client-api#51]
The definition for PowerSource is located in [include/sc2api/sc2_gametypes.h](https://github.com/Blizzard/s2client-api/blob/master/include/sc2api/sc2_gametypes.h#L195). This seems terribly out of place. Why would I want to include info about gametypes when I want the definition of a PowerSource and vice versa?

I would pull request this but I haven't had a chance to look deeply enough to figure out the best place to move it yet. Tonight, if I have a chance.

**Comment by AnthonyBrunasso** [comment]
I'd be happy to accept a pull request from you if you found a better place for it.
