### ISSUE TITLE
UnitData supply cost missing?

### ISSUE THREAD

**Issue by davechurchill** [Blizzard/s2client-api#63]
Is there anywhere to determine the supply cost of a given UnitTypeID? I only see cargo_size in UnitData, is that equivalent?

**Comment by KevinCalderone** [comment]
Looks like we are missing supply cost. We should add that.

cargo_size is something different. That is how many spots it takes up when inside a transport.

**Comment by davechurchill** [comment]
Ok, thanks for checking!

**Comment by davechurchill** [comment]
Updated the name, because I believe the mineral and vespene costs of UpgradeData are also missing

**Comment by davechurchill** [comment]
@KevinCalderone Just adding to this issue as I find things

I can't find the ABILITY_ID for UPGRADE_ID::PUNISHERGRENADES

**Comment by davechurchill** [comment]
Also a question: Can you call sc2::ABILITY_ID::RESEARCH_TERRANINFANTRYARMOR to train each successive level of armor, or do you have to call sc2::ABILITY_ID::RESEARCH_TERRANINFANTRYARMORLEVEL1, 2, 3 in that order?

**Comment by davechurchill** [comment]
sc2::ABILITY_ID::RESEARCH_SHADOWSTRIKE, supposed to be STRIDE instead of STRIKE?

**Comment by AnthonyBrunasso** [comment]
Added in 1280617259d86b0cb7e6da54244ed9c9b0befcdd it will be functional in patch 3.17
