### ISSUE TITLE
Confusing Upgrade Type Names

### ISSUE THREAD

**Issue by davechurchill** [Blizzard/s2client-api#64]
Can't find an entry in UPGRADE_ID for this:

http://wiki.teamliquid.net/starcraft2/Resonating_Glaives

**Comment by TommyTran93** [comment]
The upgrade name is UPGRADE_ID::ADEPTPIERCINGATTACK (130) although the naming could probably be more clear.

**Comment by davechurchill** [comment]
Thanks! What about this one?

http://wiki.teamliquid.net/starcraft2/SCAbility/Ventral_Sacs

**Comment by davechurchill** [comment]
One overall criticism of the upgrade names in the sc2::UPGRADE_ID namespace is that some of them use the in-game name, and some of them use a description of what they do. For example, OVERLORDSPEED, INFESTORENERGYUPGRADE describe the upgrade, CENTRIFUGALHOOKS is the in-game name. Also, the hydralisk upgrades have EVOLVE in front of the name for some reason. I think it could benefit from some clean-up such that they all use the in-game name

**Comment by TommyTran93** [comment]
Ventral sacs stop being an upgrade a while ago not exactly sure when, I think you are referring to ABILITY_ID::MORPH_OVERLORDTRANSPORT, Since each overlord must be upgraded individually.

**Comment by davechurchill** [comment]
Thank you :)

Essentially what I am currently trying to do is fill out this monstrosity of a class:
https://github.com/davechurchill/commandcenter/blob/master/src/TechTree.cpp

And since I'm not an expert in SC2 units, it's hard to figure out some of this data :)

**Comment by KevinCalderone** [comment]
I agree we should probably clean up the upgrade names. We've done a pass manually renaming a lot of the abilities, but the upgrade names are still using the raw internal name from the engine. A bunch of these are probably out of date with the name that displays in the UI.

**Comment by kuzi117** [comment]
@davechurchill would that be easier if #16 happened?

**Comment by davechurchill** [comment]
@kuzi117 Yes, but for the time being I need something in the bot, so this is what I am doing :)

**Comment by davechurchill** [comment]
Question: Can you call sc2::ABILITY_ID::RESEARCH_TERRANINFANTRYARMOR to train each successive level of armor, or do you have to call sc2::ABILITY_ID::RESEARCH_TERRANINFANTRYARMORLEVEL1, 2, 3 in that order?

Also, sc2::ABILITY_ID::RESEARCH_SHADOWSTRIKE  - STRIKE supposed to be STRIDE?

**Comment by davechurchill** [comment]
I can't find the ABILITY_ID for UPGRADE_ID::PUNISHERGRENADES

**Comment by davechurchill** [comment]
Is sc2::UPGRADE_ID::SHIELDWALL researched by sc2::ABILITY_ID::RESEARCH_COMBATSHIELD?

**Comment by KevinCalderone** [comment]
> RESEARCH_TERRANINFANTRYARMOR

Either one will work. Some of the abilities are considered "generic" abilities, where a bunch of "specific" abilities can be aliased together into single one (This is what the AbilityData::remaps_to_ability_id field means). When you try to issue a generic ability to a unit, it will actually issue whichever specific ability is currently available on the unit. In this case, the three specific level research abilities are group together into one generic ability, so you can use either one.

The primary reason we added this concept was for "Cancel". There are literally hundreds of specific cancel abilities, so it is really convenient to just have one generic Cancel. For consistency, we did a pass adding generic abilities to everything that may be useful to be grouped together.

**Comment by KevinCalderone** [comment]
> UPGRADE_ID::PUNISHERGRENADES

This is researched by "Research ConcussiveShells".

> Is sc2::UPGRADE_ID::SHIELDWALL researched by sc2::ABILITY_ID::RESEARCH_COMBATSHIELD?

Yes.

The data dump here is a good reference:
https://www.reddit.com/r/sc2ai/comments/6t31lm/a_complete_list_of_unit_ids/dlhj7h2/

If you search for "SheildWall", you can see that is the "button_name", and that we manually renamed it to the correct thing in the "friendly_name".

**Comment by KevinCalderone** [comment]
> sc2::ABILITY_ID::RESEARCH_SHADOWSTRIKE - STRIKE supposed to be STRIDE

Yes it looks like we typo'ed that. The ability says "Effect ShadowStride" which should probably be Strike.

**Comment by davechurchill** [comment]
I think it is actually stride since it's a blink ability

**Comment by davechurchill** [comment]
One last question on which abilitites produce these UPGRADE_IDs:

- MEDIVACINCREASESPEEDBOOST = sc2::ABILITY_ID::RESEARCH_HIGHCAPACITYFUELTANKS?
- HIGHCAPACITYBARRELS = ??

**Comment by KevinCalderone** [comment]
I think that is correct for MEDIVACINCREASESPEEDBOOST. I can double check tomorrow.

HIGHCAPACITYBARRELS  = Research InfernalPreigniter

**Comment by davechurchill** [comment]
Thanks Kevin!

**Comment by davechurchill** [comment]
Quick note: one upgrade has a name of "overlordspeed" in the UpgradeData.name field, whereas all other names are capitalized like OverlordSpeed

**Comment by herodrigues** [comment]
@davechurchill Can you please close this issue as you question was answered?
