### ISSUE TITLE
connect to existing server

### ISSUE THREAD

**Issue by DrRibosome** [Blizzard/s2client-api#66]
I think it would be reasonable to allow connecting to an existing server. For example, the cli args could take a host/port to connect to, instead of starting a new server process. This is particularly useful if the sc2 server is running on a remote host

**Comment by ChallengerII** [comment]
Somewhere in documentation it is mentioned that it is impossible to do the connection between more than two bots at this time. Maybe later.
And what exactly you asking to do? To create battle-net emulator? Or just plain 3rd sc2 process that serves as a host and as game observer at the same time?

**Comment by AnthonyBrunasso** [comment]
This is definitely possible to implement in the library. The game supports it as it is. Thought it's unclear to me how important it would be relative to some of our other tasks. 

Could you provide more details on your use case?

**Comment by DrRibosome** [comment]
Thanks for the attempts at answering, but I meant to put this in the deepmind pysc2 repo. Sorry for the confusion
