### ISSUE TITLE
Add a NULL value to the type enums.

### ISSUE THREAD

**Issue by KevinCalderone** [Blizzard/s2client-api#70]
Unit and Ability already have 0 reserved as NULL, but there is no enum entry for it.

We forgot to reserve 0 for Upgrade/Buff. We should change the id mapping for 0 and then also add a NULL entry to those enums.

**Comment by davechurchill** [comment]
May want to merge with https://github.com/Blizzard/s2client-api/issues/35

**Comment by KevinCalderone** [comment]
Ah didn't notice we already had an issue for this. Thanks.
