### ISSUE TITLE
How to build the api ?

### ISSUE THREAD

**Issue by raynor636** [Blizzard/s2client-api#73]
Hi,
After following the building.md tutorial in docs folder i run cmake as it is explained but i got this error
I have added the paths of the binaries to environement variable PATH for cmake and msbuild as well
Thank you 

![cmd_2017-08-14_22-33-49](https://user-images.githubusercontent.com/27637661/29290941-3960c198-8142-11e7-86e5-6d9d35974d8c.png)

**Comment by davechurchill** [comment]
Try using the MSVC developer console instead of the normal CMD console

**Comment by raynor636** [comment]
I have Visual Studio 2017 Community installed does it work with it ?

**Comment by agrutter87** [comment]
Is this your first time installing Visual Studio like it was for me? At first I didn't know what components to select, and the basic install wasn't enough. I had to select the C++ tools and all that by running the "Visual Studio Installer" and selecting "Modify". Here's the components I have selected:

![image](https://user-images.githubusercontent.com/5577935/29294991-aeef3bf4-8117-11e7-9be1-c189e182f280.png)

![image](https://user-images.githubusercontent.com/5577935/29295007-cccf4920-8117-11e7-9119-0ae214d284f2.png)

![image](https://user-images.githubusercontent.com/5577935/29295023-dc68a714-8117-11e7-9792-52f0e638b9c4.png)

![image](https://user-images.githubusercontent.com/5577935/29295027-e59ce098-8117-11e7-9661-b1a003bede2f.png)

![image](https://user-images.githubusercontent.com/5577935/29295034-ef1c9488-8117-11e7-819d-3edfce339b09.png)

I am by no means an expert on this, but I did manage to get it to build after hours of installing and uninstalling things. Also, at one point I uninstalled everything and reinstalled Visual Studio before CMake. Wasn't sure if it mattered but what the hell noobs have to just try stuff, right? LOL

**Comment by raynor636** [comment]
Thank you @agrutter87 atm i have opened the solution called bot in the project folder and it asked to install about 4 Go of packages then now i have this error

![devenv_2017-08-15_00-58-11](https://user-images.githubusercontent.com/27637661/29295783-9956df88-8156-11e7-997f-6f83e9a5277c.png)

**Comment by kuzi117** [comment]
That looks like your include directories aren't set up correctly. Did you set your project's include path?

**Comment by AnthonyBrunasso** [comment]
The bot solution is for generating the prebuilt binary solution.

The solution file you want to open is build/s2client-api.sln. Sorry for the confusion.

**Comment by raynor636** [comment]
@AnthonyBrunasso  it saying to don't tuch it 

![devenv_2017-08-15_01-17-57](https://user-images.githubusercontent.com/27637661/29296208-20db2dae-8159-11e7-9c52-a59a0053a7db.png)

**Comment by AnthonyBrunasso** [comment]
![image](https://user-images.githubusercontent.com/5962600/29296276-1d9bd4ae-810e-11e7-9300-64271201cad5.png)

**Comment by raynor636** [comment]
great ! how do you get this folder @AnthonyBrunasso ?

**Comment by AnthonyBrunasso** [comment]
It's the output of cmake, you would have created the folder and got the solution from the cmake command working in your first post.

You could alternatively download this package if you don't want to build the api from source: http://blzdistsc2-a.akamaihd.net/SC2API_Binary_vs2017.zip

**Comment by raynor636** [comment]
yes @davechurchill said to build it inside MSVC so i've started something and i found myself doing something else, i've tryed again cmake and i still got the same error

![cmake-gui_2017-08-15_01-30-50](https://user-images.githubusercontent.com/27637661/29296505-088238e0-815b-11e7-83d3-66858792b448.png)
![cmake-gui_2017-08-15_01-31-19](https://user-images.githubusercontent.com/27637661/29296504-087b4c24-815b-11e7-952a-25c43620e114.png)

**Comment by AnthonyBrunasso** [comment]
If you want to build from source please follow our building docs (https://github.com/Blizzard/s2client-api/blob/master/docs/building.md) and you'll likely need to install the components @agrutter87 recommended, this is actually a step I was not aware of so I'll have to update our docs appropriately, thank you, agrutter. Basically your environment needs to be set up in such a way that cmake finds your compiler.

If you download http://blzdistsc2-a.akamaihd.net/SC2API_Binary_vs2017.zip that package comes with prebuilt library files so you don't have to worry about any of this. You should just be able to extract it somewhere and open bot.sln and build.

**Comment by raynor636** [comment]
it would be nice to have a tutorial on yt explaining how to do it from the starting point
thx @AnthonyBrunasso for the package it worked !

![2017-08-15_01-51-45](https://user-images.githubusercontent.com/27637661/29297034-664ca99e-815e-11e7-8615-5d1137660794.gif)

**Comment by AnthonyBrunasso** [comment]
Glad I could help @raynor636! 

I will close this issue unless you have any other questions.

**Comment by raynor636** [comment]
it's okey @AnthonyBrunasso the issue is closed and now i am on the code
so it worked by installing in VS the components that @agrutter87 talked about and then i was abeld to build it by running the command and steps of building.md 
https://youtu.be/TTrO-HQLBdQ

**Comment by sihuaiwei** [comment]
@raynor636 Where is bot.exe? need install StarCraft II？when i make successful ,i do not know how to run the example ,and where is bot.exe

**Comment by raynor636** [comment]
When it build you need to open the solution and compile everything but it should be another issue if you can open it it can be cool

![2017-08-18_12-50-37](https://user-images.githubusercontent.com/27637661/29456366-9b9e999a-8415-11e7-9fd2-b76fcad8bb8d.png)

**Comment by sihuaiwei** [comment]
@raynor636 i what now in windows, after start s2client-api.sln do what?

**Comment by raynor636** [comment]
let's move here https://github.com/Blizzard/s2client-api/issues/93
