### ISSUE TITLE
Examples CMakeLists file missing a dependancy?

### ISSUE THREAD

**Issue by ArlingtonDawson** [Blizzard/s2client-api#80]
Had an issue building the feature_layer example due to a missing dependency.

When I edited the following code at line 45:
`target_link_libraries(feature_layers sc2api sc2utils sc2renderer)` to `target_link_libraries(feature_layers sc2api sc2utils sc2renderer libvcruntime)`

It resolved the issue.

**Comment by KevinCalderone** [comment]
What was the linker error you were seeing? Was it just feature_layers failing?

**Comment by ArlingtonDawson** [comment]
This was the linker error I had.

`MSVCRTD.lib(_chandler4gs_.obj) : error LNK2019: unresolved external symbol __except_handler4_common referenced in function __except_handler4`

**Comment by KevinCalderone** [comment]
I've seen that error when you build it as a 32-bit target. Is this was you are doing?

Our docs say to build it as 64-bit as that is all we have been testing:
cmake ../ -G "Visual Studio 15 Win64"

Does it still occur when you use that cmake command line? Do you need 32-bit support?

**Comment by ArlingtonDawson** [comment]
Thank you, very much. That resolved the issue.
