### ISSUE TITLE
Compiling error sc2api.pb.h not found

### ISSUE THREAD

**Issue by erri120** [Blizzard/s2client-api#83]
I cloned the repository and started with the docs. After the first tutorial I wanted to compile the code using the gcc compiler on windows:
`gcc -Wall -c -I../include/ tutorial.cc -std=c++11`
When I use this command the gcc has a fatal error:
`In file included from ../include/sc2api/sc2_unit.h:6:0,
                 from ../include/sc2api/sc2_interfaces.h:13,
                 from ../include/sc2api/sc2_api.h:3,
                 from tutorial.cc:1:
../include/sc2api/sc2_proto_interface.h:5:23: fatal error: sc2api.pb.h: No such file or directory
compilation terminated.`
The sc2_proto_interface.h file includes the sc2api.pb.h file, that is not in the repository. Is the file in the SC2 dir? If so how should I change my command for compile my code.

**EDIT:**
found this [https://us.battle.net/forums/en/sc2/topic/20758537485](url) and they found a solution for using the make command on linux. What can I do on windows?

**Comment by AnthonyBrunasso** [comment]
You'll want to follow the doc in https://github.com/Blizzard/s2client-api/blob/master/docs/building.md

Basically the files it's looking for are auto generated protocol files. In order to build them protobuf and protoc must be built. Cmake sets up those dependencies and outputs a make file for you.

I believe the exact command for cmake you'll want to use is: cmake ..\ -G "Unix Makefiles" if you are trying to use gcc on windows I assume you have make available to you as well.

**Comment by erri120** [comment]
Virtual Studio just failed to build the project for some reason. After reinstalling it worked.

**Comment by sihuaiwei** [comment]
@erri120 Do you slove your problem ? I have the problrem fatal error: sc2api.pb.h: No such file or directory compilation terminated  on linux

**Comment by alkurbatov** [comment]
Hi @erri120 ,
You should build the api first. *.pb.h is the authoganerated header located in build/generated folder.

**Comment by erri120** [comment]
@sihuaiwei just follow the doc (building.md) like @AnthonyBrunasso pointed out. When you made the files using cmake you need to go to the directory and start the s2client-api.sln, if you don't start the project from this file sc2api.pb.h won't be created.

**Comment by N00byEdge** [comment]
This is something that I got a lot after pulling the /contrib/ projects separately. Recloning recursively fixes this. Perhaps something should be done so that the file doesn't fail to generate if the other projects aren't pulled with the recursive clone.

**Comment by kuzi117** [comment]
It's reasonable to check if the contrib repos exist in the cmake build and fail there. I might be able to add this as part of my PR for installs
