### ISSUE TITLE
Cmake not found files

### ISSUE THREAD

**Issue by sihuaiwei** [Blizzard/s2client-api#88]
three day i have a problem ,when i cmake install the erros :
CMake Error at contrib/civetweb/src/cmake_install.cmake:50 (file):
  file INSTALL cannot find
  "/home/sihuaiwei/桌面/git/s2client-api/build/bin/civetweb".
Call Stack (most recent call first):
  contrib/civetweb/cmake_install.cmake:37 (include)
  cmake_install.cmake:37 (include)

**Comment by AnthonyBrunasso** [comment]
Did you get the contrib libraries in your clone? 

From the root of the repo can you run: git submodule update --init --recursive 

And try again?

**Comment by sihuaiwei** [comment]
In linux, I according the  https://github.com/Blizzard/s2client-api/blob/master/docs/building.md clone the code ,when i make install the erros is coming ;
![default](https://user-images.githubusercontent.com/13798013/29415817-d52ef3fa-8396-11e7-9614-4c8f70bfbb5f.png)

**Comment by AnthonyBrunasso** [comment]
Oh leave out install, there is no install target.

just run "make" or "make bot_simple" for instance.

**Comment by kuzi117** [comment]
How much of a pain would it be to provide an install target and find package cmake file?  Is there a reason there isn't one provided?

**Comment by sihuaiwei** [comment]
ok,thank you very much ,but when i run the example the error : 
fatal error: sc2api/sc2_api.h:not found ,how run a example ,i am very confused .........  hope help

**Comment by AnthonyBrunasso** [comment]
In your screenshot you've appeared to build all the targets without error. Can you screenshot the error you are currently having?

**Comment by AnthonyBrunasso** [comment]
@kuzi117 I don't think we have a good reason other than we haven't had the time to get around to it. It's definitely something worth looking into for us though. Thank you.

**Comment by sihuaiwei** [comment]
@AnthonyBrunasso when i used example : #include <sc2api/sc2_api.h>
#include <iostream>
using namespace sc2;
..............................................
![default](https://user-images.githubusercontent.com/13798013/29439899-7babc760-83f3-11e7-8f9c-4baa17713365.png)
the chinese means there is no file or directory
how use the example
