### ISSUE TITLE
SC2 Client - Remote desktop connection

### ISSUE THREAD

**Issue by mhogersdeepmind** [Blizzard/s2client-api#89]
Dear all, 

Due to the flexible scaling possibilities of amazon web services I had decided to use one of their instances for testing. Unfortunately it seems that access to SC2 is impossible. I tried running the CommandCenter bot of davechurchill and the game itself, with no good outcome.
The error is as follows, "Running StarCraft II through a Remote Desktop connection is not supported. Exiting program." I am relatively new to most of this, so I wonder whether this can be circumvented?

Regards,

Michael

**Comment by dsjoerg** [comment]
Back in the day you could use VNC instead.

**Comment by AnthonyBrunasso** [comment]
Unfortunately our windows binary does not run in a VM. The headless linux build does though if that's a possibility for you.
