### ISSUE TITLE
How do i mak my first AI ?

### ISSUE THREAD

**Issue by raynor636** [Blizzard/s2client-api#93]
This is the conitunuation of the issue "How to build the API" https://github.com/Blizzard/s2client-api/issues/73

**Comment by sihuaiwei** [comment]
I bulid the project 
![default](https://user-images.githubusercontent.com/13798013/29457223-d2dca93e-844b-11e7-9e19-9b98b5880c8a.png)
![default](https://user-images.githubusercontent.com/13798013/29457233-dedab94c-844b-11e7-9d6f-c0e65ee54df5.png)
next step  What should I do?

**Comment by raynor636** [comment]
thx @sihuaiwei this is actually what i am trying to find on yt 🔢

**Comment by sihuaiwei** [comment]
sorry , I see that 
![default](https://user-images.githubusercontent.com/13798013/29457400-9700f5ea-844c-11e7-92dc-11daa99a4f15.png)

**Comment by sihuaiwei** [comment]
@raynor636 what is this 
![default](https://user-images.githubusercontent.com/13798013/29457498-fb85c8b0-844c-11e7-975e-33b8bf91f90b.png)

**Comment by DrFriday** [comment]
I think I can help you guys out, I just need to get off work in a few hours.

**Comment by AnthonyBrunasso** [comment]
After following the cmake steps in our build docs open s2client-api.sln and build the API with visual studio. Alternatively open and build one of the examples.

**Comment by sihuaiwei** [comment]
@AnthonyBrunasso When start  s2client-api.sln build the s2client-api,and run tutorial.cc the errror is : 
 
![default](https://user-images.githubusercontent.com/13798013/29482044-5a70be24-84bc-11e7-9325-e680650f4616.png)
the chinese means Cannot start
![default](https://user-images.githubusercontent.com/13798013/29482054-9bd0f6f4-84bc-11e7-8dd3-78f46f7c0fa7.png)
Access denied: 
hope you  help   think you very much！

**Comment by sihuaiwei** [comment]
I want to know which version of StarCraft 2 is available under windows. Can you give me a download connection?

**Comment by alkurbatov** [comment]
@sihuaiwei I believe you need to buy it
http://eu.battle.net/sc2/ru/legacy-of-the-void/

**Comment by sihuaiwei** [comment]
@alkurbatov it is 25G??????????

**Comment by alkurbatov** [comment]
I believe that depends on the platform you use. On Mac it is much larger.

**Comment by LiquidWater** [comment]
theres a 2GB linux headless client that you can use

**Comment by davinnovation** [comment]
build your solution with ALL_BUILD, and go to 'bin' folder. there's something you want... .exe s

**Comment by sihuaiwei** [comment]
@davinnovation  I  know in windows, but linux how run in bin

**Comment by AnthonyBrunasso** [comment]
Just run make with the target you want to build. For example:

make bot_simple

Then I believe the binary is in build/src. You must supply the location of the executable when you run it. For example:

./bot_simple -e /home/user/sc2

Where /home/user/sc2 is your path.

**Comment by KevinCalderone** [comment]
To amend Anthony's comment above, the binary is probably located at build/bin/bot_simple.

Closing this out to keep our issues list clean. If you still can't figure this out, feel free to reopen this.
