### ISSUE TITLE
missing headers

### ISSUE THREAD

**Issue by breadbread1984** [Blizzard/s2client-api#94]
I get the following error when compiling
![screenshot_20170818_221003](https://user-images.githubusercontent.com/1930282/29462476-15b2455a-8462-11e7-9c5b-8b08de047d2f.png)
I know the missing headers can be generated from proto files of s2client-proto project. but where should I put them?

**Comment by kuzi117** [comment]
You shouldn't have to put them anywhere. They should be generated into `build/generated` and the cmake script should be using them to build from there.

**Comment by breadbread1984** [comment]
I just cloned the source from git and put dep libs into contrib. What else shall I do to avoid the problem. Thx

**Comment by kuzi117** [comment]
Put dep libs into contrib? Did you clone with the `--recursive` flag as in the [build docs](https://github.com/Blizzard/s2client-api/blob/master/docs/building.md)?

**Comment by breadbread1984** [comment]
oh I miss it. it is solved. thx.

**Comment by kuzi117** [comment]
No problem :)

**Comment by sihuaiwei** [comment]
@breadbread1984 On linux after make how run the example?

**Comment by breadbread1984** [comment]
I am solving another problem of installing the api. I may ask you for help when I catch up with your pace.
