### ISSUE TITLE
Hook up Travis CI.

### ISSUE THREAD

**Issue by AnthonyBrunasso** [Blizzard/s2client-api#95]
Soon.

**Comment by kuzi117** [comment]
Is this dependent on #15?

**Comment by AnthonyBrunasso** [comment]
There's some challenges running the tests because the binary has to be run. I haven't used Travis much before so I'll need to research if that's even something possible.

A good first step is just making sure everything builds on our desired platforms for each commit.

**Comment by Michael-F-Bryan** [comment]
It may be a good idea to add an `after_success` hook which builds the documentation and pushes it to GitHub Pages so users can browse it online instead of building locally. I do [something similar] for most of my projects.

[something similar]: https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/c9a1f6dd1538c9fbbd6028eb18ec6e1bc5d54eff/.travis.yml#L17

**Comment by AnthonyBrunasso** [comment]
@Michael-F-Bryan I like this idea. I'll have to check on the status of our travis work on Monday.

**Comment by alkurbatov** [comment]
I created initial version of Travis config which works for Linux builds, see #187. Probably OS X support will be introduced later.

From my point of view the real problem of Travis is outdated build environment (here we choose between Ubuntu Trusty (12.04) and some even older version). That cause a lot of problems for modern C++ (that could be clearly seen in the pull-request). So I am not sure that tests and SC2 can be used inside a Travis Virtual Machine without additional magic.

**Comment by alkurbatov** [comment]
I implemented os x support too. Feel free to reuse the code:
https://github.com/alkurbatov/suvorov-bot/blob/master/.travis.yml

**Comment by herodrigues** [comment]
@AnthonyBrunasso Travis build already exists.

https://travis-ci.org/Blizzard/s2client-api
