### ISSUE TITLE
Which the version of StarCraft 2 used?

### ISSUE THREAD

**Issue by sihuaiwei** [Blizzard/s2client-api#96]
everybody
I can not find the API used StarCraft 2, download connection?

**Comment by kuzi117** [comment]
I'm not sure what you're asking. This _is_ the API. If you're looking for which version of StarCraft 2 is required to use the API, it is the latest version available from the Blizzard launcher. [You can buy it here](https://us.battle.net/shop/en/product/starcraft-ii-legacy-of-the-void) if you don't have it already, though I'm sure there's a region specific site you should use.

**Comment by kuzi117** [comment]
Wait, your using Ubuntu, aren't you?
