### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by breadbread1984** [Blizzard/s2client-api#97]
I run into the following error when I install s2client-api
![screenshot_20170819_235120](https://user-images.githubusercontent.com/1930282/29488240-6ba83aa0-8539-11e7-9978-caae3d3a8374.png)
How can I get rid of this problem. Thx

**Comment by kuzi117** [comment]
Installing does not work right now. I'm working on it right now in #90. Consider the solution from CommandCenter until then.

**Comment by breadbread1984** [comment]
OK
